// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5lvr_NfulBGh-IoDTC9GOipVCkvo_Id4',
    appId: '1:948522066980:web:944e4f4390c01d71d0a4b1',
    messagingSenderId: '948522066980',
    projectId: 'oto-service-app',
    authDomain: 'oto-service-app.firebaseapp.com',
    storageBucket: 'oto-service-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHvFQrQDNeLhTCWfpyxO5zxd_PoNxsfyc',
    appId: '1:948522066980:android:68bde87b6af688ead0a4b1',
    messagingSenderId: '948522066980',
    projectId: 'oto-service-app',
    storageBucket: 'oto-service-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBoRhpnlfGLolI2sbBapgK1pO_j1fT1W8',
    appId: '1:948522066980:ios:bfa8726b099b8795d0a4b1',
    messagingSenderId: '948522066980',
    projectId: 'oto-service-app',
    storageBucket: 'oto-service-app.firebasestorage.app',
    iosBundleId: 'com.example.otoService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBoRhpnlfGLolI2sbBapgK1pO_j1fT1W8',
    appId: '1:948522066980:ios:bfa8726b099b8795d0a4b1',
    messagingSenderId: '948522066980',
    projectId: 'oto-service-app',
    storageBucket: 'oto-service-app.firebasestorage.app',
    iosBundleId: 'com.example.otoService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5lvr_NfulBGh-IoDTC9GOipVCkvo_Id4',
    appId: '1:948522066980:web:bb8d6e7a07658eb1d0a4b1',
    messagingSenderId: '948522066980',
    projectId: 'oto-service-app',
    authDomain: 'oto-service-app.firebaseapp.com',
    storageBucket: 'oto-service-app.firebasestorage.app',
  );
}
